//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuongPho
    {
        public int ma_duongpho { get; set; }
        public string ten_duongpho { get; set; }
        public Nullable<int> ma_phuongxa { get; set; }
        public string ghichu { get; set; }
    }
}
