//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int ma_lienhe { get; set; }
        public string ten_lienhe { get; set; }
        public Nullable<System.Guid> ma_tinrao { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string didong { get; set; }
        public string email { get; set; }
        public string ghichu { get; set; }
    }
}
