//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanXet
    {
        public int id { get; set; }
        public Nullable<System.Guid> ma_tinrao { get; set; }
        public Nullable<int> ma_baiviet { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> thanhvien { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string ghichu { get; set; }
    }
}
