//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int? ma_taikhoan { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string xacnhan_matkhau { get; set; }
        public string tennguoidung { get; set; }
        public string anhdaidien { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string dienthoai { get; set; }
        public Nullable<int> maquyen { get; set; }
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public string ghichu { get; set; }
    }
}
