//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinRaoCMCT
    {
        public System.Guid ma_tinrao { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public Nullable<int> ma_loaihinh { get; set; }
        public Nullable<int> ma_ndloaihinh { get; set; }
        public Nullable<int> ma_tinhtp { get; set; }
        public Nullable<int> ma_quanhuyen { get; set; }
        public Nullable<int> ma_phuongxa { get; set; }
        public Nullable<int> ma_duongpho { get; set; }
        public Nullable<double> gia_tu { get; set; }
        public Nullable<double> gia_den { get; set; }
        public Nullable<int> ma_donvi { get; set; }
        public Nullable<double> dientich_tu { get; set; }
        public Nullable<double> dientich_den { get; set; }
        public string anh1 { get; set; }
        public string anh2 { get; set; }
        public string anh3 { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public Nullable<System.DateTime> ngaykethuc { get; set; }
        public string ghichu { get; set; }
    }
}
