//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinRaoCBCHT
    {
        public System.Guid ma_tinrao { get; set; }
        public string tieude { get; set; }
        public Nullable<int> ma_loaihinh { get; set; }
        public Nullable<int> ma_ndloaihinh { get; set; }
        public Nullable<int> ma_tinhtp { get; set; }
        public Nullable<int> ma_quanhuyen { get; set; }
        public Nullable<int> ma_phuongxa { get; set; }
        public Nullable<int> ma_duongpho { get; set; }
        public Nullable<double> dientich { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<int> ma_donvi { get; set; }
        public string mota { get; set; }
        public Nullable<int> so_phongngu { get; set; }
        public Nullable<int> so_phongkhach { get; set; }
        public Nullable<int> so_nhabep { get; set; }
        public Nullable<int> so_toilet { get; set; }
        public string anh1 { get; set; }
        public string anh2 { get; set; }
        public string anh3 { get; set; }
        public string anh4 { get; set; }
        public string anh360do { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public string ghichu { get; set; }
    }
}
