//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMuaBanNhaDat1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaDo
    {
        public int ma_toado { get; set; }
        public Nullable<System.Guid> ma_tinrao { get; set; }
        public Nullable<float> lat1 { get; set; }
        public Nullable<float> lng1 { get; set; }
        public Nullable<float> lat2 { get; set; }
        public Nullable<float> lng2 { get; set; }
        public Nullable<float> lat3 { get; set; }
        public Nullable<float> lng3 { get; set; }
        public Nullable<float> lat4 { get; set; }
        public Nullable<float> lng4 { get; set; }
        public Nullable<float> lat5 { get; set; }
        public Nullable<float> lng5 { get; set; }
        public Nullable<float> lat6 { get; set; }
        public Nullable<float> lng6 { get; set; }
    }
}
